apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-clients
  namespace: casapp
  labels:
    app: msvc-clients
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-clients
  template:
    metadata:
      labels:
        app: msvc-clients
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - image: dwinpaez/msvc-clients:latest
          name: msvc-clients
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILE
              value: "prod"
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-clients
                  key: msvc_port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: msvc-clients
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: msvc-clients
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msvc-clients
                  key: db_password
            - name: BOOKINGS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-clients
                  key: msvc_bookings_url
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
