apiVersion: v1
kind: ConfigMap
metadata:
  namespace: casapp
  name: msvc-clients
data:
  msvc_port: "8081"
  db_name: "casapp_clients"
  db_username: "casapp_user"
  msvc_bookings_url: "msvc-bookings:8002/booking"
  application.yaml: |-
    client:
      message: Default Clients
    server:
      port: 8081
    ---  
    spring:
      config:
        activate:
          on-profile: dev
    client:
      message: Dev Clients
    ---
    spring:
      config:
        activate:
          on-profile: local
    client:
      message: Local Clients   

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: casapp
  name: msvc-bookings
data:
  msvc_port: "8082"
  db_name: "casapp_bookings"
  db_username: "casapp_user"
