apiVersion: v1
kind: ConfigMap
metadata:
  namespace: casapp
  name: msvc-clients
data:
  msvc_port: "8081"
  db_name: "casapp_clients"
  db_username: "casapp_user"
  msvc_bookings_url: "msvc-bookings:8002/booking"
  msvc-clients.yml: |-
    client:
      message: Default Clients
    ---
    spring:
      config:
        activate:
          on-profile: dev
    client:
      message: Dev Clients
    ---
    spring:
      config:
        activate:
          on-profile: prod
    client:
      message: Prod Clients

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: casapp
  name: msvc-bookings
data:
  msvc_port: "8082"
  db_name: "casapp_bookings"
  db_username: "casapp_user"
  msvc-bookings.yml: |-
    client:
      message: Default Clients
