apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: casapp
  name: msvc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      role: msvc-gateway
  template:
    metadata:
      labels:
        role: msvc-gateway
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: msvc-gateway
          image: dwinpaez/msvc-gateway:latest
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-gateway
  namespace: casapp
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    role: msvc-gateway


