apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-clients
  namespace: casapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-clients
  template:
    metadata:
      labels:
        app: msvc-clients
    spec:
      containers:
        - name: msvc-clients
          image: dwinpaez/msvc-clients:latest
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-clients
                  key: msvc_port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: msvc-clients
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: msvc-clients
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msvc-clients
                  key: db_password
            - name: BOOKINGS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-clients
                  key: msvc_bookings_url