apiVersion: v1
kind: Service
metadata:
  name: msvc-bookings
  namespace: casapp
spec:
  type: LoadBalancer
  ports:
    - port: 8002
      protocol: TCP
      targetPort: 8082
  selector:
    app: msvc-bookings